// Code generated by MockGen. DO NOT EDIT.
// Source: ./dependencies.go

// Package app_test is a generated GoMock package.
package app_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockCurrencyConverter is a mock of CurrencyConverter interface.
type MockCurrencyConverter struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyConverterMockRecorder
}

// MockCurrencyConverterMockRecorder is the mock recorder for MockCurrencyConverter.
type MockCurrencyConverterMockRecorder struct {
	mock *MockCurrencyConverter
}

// NewMockCurrencyConverter creates a new mock instance.
func NewMockCurrencyConverter(ctrl *gomock.Controller) *MockCurrencyConverter {
	mock := &MockCurrencyConverter{ctrl: ctrl}
	mock.recorder = &MockCurrencyConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyConverter) EXPECT() *MockCurrencyConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockCurrencyConverter) Convert(arg0 context.Context, amount decimal.Decimal, from, to string) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", arg0, amount, from, to)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockCurrencyConverterMockRecorder) Convert(arg0, amount, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockCurrencyConverter)(nil).Convert), arg0, amount, from, to)
}
